### Завдання 1)
\begin{equation}
3, 4, 5, 6, 7,8, 9, 13, 19
\end{equation} 

### Завдання 2)
\begin{equation}
\begin{cases}
    2x_1 + x_2 - 5x_3 + x_4 = 8 \\
    x_1 - 3x_2 - 6x_4 = 9 \\
    2x_1 - x_3 + 2x_4 = -5 \\
    x_1 + 4x_2 - 7x_3 + 6x_4 = 0 \\
\end{cases}
\end{equation} 

### Завдання 3)
\begin{equation}
2(A - 0,5B) + AB  \\
де A = \begin{bmatrix}
    5 & 3 & -1 \\
    2 & -2 & 0 \\
    3 & -1 & 2
\end{bmatrix},
B = \begin{bmatrix}
    1 & 4 & 16 \\
    -3 & -2 & 0 \\
    5 & 7 & 2
\end{bmatrix}
\end{equation}

In [1]:
import numpy as np

In [2]:
def task3_1(n, m, r, c):
    arr = np.ones((n, m))
    arr[::r, ::1] = 0
    arr[::1, ::c] = 0
    return arr

def task3_2(n, m, r, c):
    arr = []
    for i in range(n):
        row = []
        for j in range(m):
            row.append(1)
        arr.append(row)

    for i in range(n):
        for j in range(m):
            if(i%r == 0 or j%c == 0):
                arr[i][j] = 0
    return arr

def task4_1(n, m):
    matrix = np.zeros((n, m))
    matrix[0] = np.arange(m)
    return matrix

def task4_2(n, m):
    matrix = []
    for i in range(n):
        if i == 0:
            matrix.append(list(range(m)))
        else:
            matrix.append([0] * m)
    return matrix

def task5_1(n):
    arr = np.zeros((n, n))
    arr[::2] = 1
    return arr

def task5_2(n):
    matrix = []
    for i in range(n):
        if i % 2 == 0:
            matrix.append([1] * n)
        else:
            matrix.append([0] * n)
    return matrix

def task6_1(arr):
    return np.where(arr != 0, -1, arr)

def task6_2(arr):
    for i in range(len(arr)):
        if arr[i] != 0:
            arr[i] = -1
    return arr

def task7_1(arr):
    return np.where(arr == 0, -1, arr)

def task7_2(arr):
    for i in range(len(arr)):
        if arr[i] == 0:
            arr[i] = -1
    return arr

def task8_1(arr):
    zero_count = np.count_nonzero(arr == 0)
    non_zero_count = len(arr) - zero_count
    return zero_count, non_zero_count

def task8_2(arr):
    zero_count = sum(1 for num in arr if num == 0)
    non_zero_count = len(arr) - zero_count
    return zero_count, non_zero_count

def task9_1(n):
    return np.arange(n, -1, -1)

def task9_2(n):
    return [i for i in range(n, -1, -1)]

def task13_1_test():
    row_even = np.array([0, 1] * 400)
    row_odd = np.array([1, 0] * 400)
    chessboard = np.row_stack([row_even, row_odd] * 400)
    return chessboard

def task13_2_test():
    chessboard = [[(i + j) % 2 for j in range(800)] for i in range(800)]
    return chessboard

def task13_1():
    row_even = np.array([0, 1] * 4)
    row_odd = np.array([1, 0] * 4)
    chessboard = np.row_stack([row_even, row_odd] * 4)
    return chessboard

def task13_2():
    chessboard = [[(i + j) % 2 for j in range(8)] for i in range(8)]
    return chessboard

def task19_1(n):
    return np.linspace(0, 1, n+1, endpoint=False)[1:]

def task19_2(n):
    interval = 1 / (n+1)
    vector = [interval * i for i in range(1, n+1)]
    return vector

In [3]:
%time res3_1 = task3_1(1000,1000,2,3)
%time res3_2 = task3_2(1000,1000,2,3)
print(task3_1(6,7,2,3))
result_task3_2 = task3_2(6,7,2,3)
for num in result_task3_2:
    print(num)

CPU times: total: 0 ns
Wall time: 10 ms
CPU times: total: 172 ms
Wall time: 192 ms
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0.]]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]


In [4]:
%time res4_1 = task4_1(1000,1000)
%time res4_2 = task4_2(1000,1000)
print(task4_1(3,4))
result_task4_2 = task4_2(3,4)
for num in result_task4_2:
    print(num)

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 19 ms
[[0. 1. 2. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0, 1, 2, 3]
[0, 0, 0, 0]
[0, 0, 0, 0]


In [5]:
%time res5_1 = task5_1(1000)
%time res5_2 = task5_2(1000)
print(task5_1(5))
result_task5_2 = task5_2(5)
for num in result_task5_2:
    print(num)

CPU times: total: 0 ns
Wall time: 5 ms
CPU times: total: 0 ns
Wall time: 32 ms
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]
[1, 1, 1, 1, 1]
[0, 0, 0, 0, 0]
[1, 1, 1, 1, 1]
[0, 0, 0, 0, 0]
[1, 1, 1, 1, 1]


In [6]:
arr = np.random.randint(0, 11, size=100000)
%time res6_1 = task6_1(arr)
%time res6_2 = task6_2(arr)
print(task6_1(np.array([3, 4, 0, 9, 7, 0, 6, 0, 4, 0, 3])))
print(task6_2([3, 4, 0, 9, 7, 0, 6, 0, 4, 0, 3]))

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 33 ms
[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]
[-1, -1, 0, -1, -1, 0, -1, 0, -1, 0, -1]


In [7]:
arr = np.random.randint(0, 11, size=100000)
%time res7_1 = task7_1(arr)
%time res7_2 = task7_2(arr)
print(task7_1(np.array([3, 4, 0, 6, 5, 0, 3, 0, 4])))
print(task7_2([3, 4, 0, 6, 5, 0, 3, 0, 4]))

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 24 ms
[ 3  4 -1  6  5 -1  3 -1  4]
[3, 4, -1, 6, 5, -1, 3, -1, 4]


In [8]:
arr = np.random.randint(0, 11, size=100000)
%time res8_1 = task8_1(arr)
%time res8_2 = task8_2(arr)
print(task8_1(np.array([3, 4, 0, 9, 8, 2, 4, 0, 8, 4, 0])))
print(task8_2([3, 4, 0, 9, 8, 2, 4, 0, 8, 4, 0]))

CPU times: total: 0 ns
Wall time: 1 ms
CPU times: total: 0 ns
Wall time: 15 ms
(3, 8)
(3, 8)


In [9]:
%time res9_1 = task9_1(100000)
%time res9_2 = task9_2(100000)
print(task9_1(10))
print(task9_2(10))

CPU times: total: 0 ns
Wall time: 1e+03 µs
CPU times: total: 0 ns
Wall time: 4 ms
[10  9  8  7  6  5  4  3  2  1  0]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [10]:
%time res13_1 = task13_1_test()
%time res13_2 = task13_2_test()
print(res13_1.shape)
print("("+str(len(res13_2))+", "+str(len(res13_2[0]))+")")
print(task13_1())
result_task13_2 = task13_2()
for num in result_task13_2:
    print(num)

CPU times: total: 0 ns
Wall time: 4 ms
CPU times: total: 15.6 ms
Wall time: 90 ms
(800, 800)
(800, 800)
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]


In [11]:
%time res19_1 = task19_1(100000)
%time res19_2 = task19_2(100000)
print([f"{num:.3f}" for num in task19_1(10)])
print([f"{num:.3f}" for num in task19_2(10)])

CPU times: total: 0 ns
Wall time: 2 ms
CPU times: total: 0 ns
Wall time: 15 ms
['0.091', '0.182', '0.273', '0.364', '0.455', '0.545', '0.636', '0.727', '0.818', '0.909']
['0.091', '0.182', '0.273', '0.364', '0.455', '0.545', '0.636', '0.727', '0.818', '0.909']
