In [1]:
import numpy as np

In [2]:
A_np = np.array([[5, 3, -1],
              [2, -2, 0],
              [3, -11, 2]])

B_np = np.array([[1, 4, 16],
              [-3, -2, 0],
              [5, 7, 2]])

In [3]:
result_np = 2 * (A_np - 0.5 * B_np) + np.dot(A_np, B_np)

In [4]:
A_it = [[5, 3, -1],
     [2, -2, 0],
     [3, -11, 2]]

B_it = [[1, 4, 16],
     [-3, -2, 0],
     [5, 7, 2]]

In [5]:
result_iter = []
for i in range(len(A_it)):
    row = []
    for j in range(len(A_it[0])):
        val = 2 * (A_it[i][j] - 0.5 * B_it[i][j]) + A_it[i][0] * B_it[0][j] + A_it[i][1] * B_it[1][j] + A_it[i][2] * B_it[2][j]
        row.append(val)
    result_iter.append(row)

In [6]:
print(result_np)
for row in result_iter:
   print(row)

[[ 0.  9. 60.]
 [15. 10. 32.]
 [47. 19. 54.]]
[0.0, 9.0, 60.0]
[15.0, 10.0, 32.0]
[47.0, 19.0, 54.0]


In [7]:
print(np.allclose(result_np, result_iter))

True


In [8]:
%%timeit
result_np = 2 * (A_np - 0.5 * B_np) + np.dot(A_np, B_np)

14.2 µs ± 1.82 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [9]:
%%timeit
result_iter = []
for i in range(len(A_it)):
    row = []
    for j in range(len(A_it[0])):
        val = 2 * (A_it[i][j] - 0.5 * B_it[i][j]) + A_it[i][0] * B_it[0][j] + A_it[i][1] * B_it[1][j] + A_it[i][2] * B_it[2][j]
        row.append(val)
    result_iter.append(row)

10.2 µs ± 1.45 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
